### ISSUE TITLE
Error: ENOENT: no such file or directory, stat 'build/public'

### ISSUE THREAD

**Issue by yixuanhouphl** [netlify-labs/netlify-plugin-a11y#19]
Hi there,

I can run this plug-in locally successfully. However, when I deploy the site on Netlify. I'm getting this error message(see screenshot). Can you please advise a solution to this error?
![Screen Shot 2020-05-04 at 2 08 49 PM](https://user-images.githubusercontent.com/32692261/80931889-ca20f580-8e10-11ea-8566-775aba325401.png)

**Comment by ehmicky** [comment]
Hi @yixuanhouphl,

I just submitted a PR at #20 to fix this problem.

**Comment by yixuanhouphl** [comment]
@ehmicky thanks for the quick response. I just re-ran it and still am getting the same error. Do I need to change anything from my side?

**Comment by yixuanhouphl** [comment]
@sw-yx @ehmicky do you know why it always says the folder I indicate doesn't exist? I do have the folder named public in the root directory of my repo. And the plug-in works locally, why it can't find the folder on Netlify? Did I set up something wrong?

**Comment by ehmicky** [comment]
Could you please share your deploy logs (like the screenshot above)? Thanks.

**Comment by yixuanhouphl** [comment]
> Could you please share your deploy logs (like the screenshot above)? Thanks.

![Screen Shot 2020-05-06 at 8 51 20 AM](https://user-images.githubusercontent.com/32692261/81114811-d45d0400-8f76-11ea-9764-46f080f989f5.png)
![Screen Shot 2020-05-06 at 8 52 36 AM](https://user-images.githubusercontent.com/32692261/81114899-f6568680-8f76-11ea-9467-9eb7c47d92b3.png)

**Comment by yixuanhouphl** [comment]
@ehmicky This is the netlify.toml file. Regarding the checkpath, I did use '/public', '/src', which doesn't work as well
![Screen Shot 2020-05-06 at 8 53 28 AM](https://user-images.githubusercontent.com/32692261/81114974-18e89f80-8f77-11ea-8707-c973c415d390.png)


This is my repo 
![Screen Shot 2020-05-06 at 8 55 14 AM](https://user-images.githubusercontent.com/32692261/81115167-6402b280-8f77-11ea-9ed5-b5d62cb0f91f.png)
structure.

**Comment by ehmicky** [comment]
The `checkPaths` are relative to your publish directory `build/` and must refer to existing files. It seems like `build/repo/public` does not exist, which is creating this error message.

**Comment by yixuanhouphl** [comment]
@ehmicky As you can see my public and src folders are in the same directory as netlify.toml (build/repo/netlify.toml), why the checkpath I defined says it doesn't exist?
