### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by matuzo** [netlify-labs/netlify-plugin-a11y#5]
Hey, thanks for the plugin! I'd love to use it on all of my sites, but unfortunately it doesn't work for me (all the time).

**Describe the bug**
If I try to deploy by pushing to master, it seems that it never works.  (see screenshot) If I trigger a manual deployment in the netlify backend it works sometimes.

What kind of information do you need to track down the error?

netlify.toml

```
[[plugins]]
package = "netlify-plugin-a11y"

  # all inputs are optional, we just show you the defaults below
  [plugins.inputs]

  ## Another checkPaths Example 
  checkPaths = ['/']
```

Repo: https://github.com/matuzo/front-end-bookmarks

**Screenshots**
![Screen Shot 2020-04-27 at 07 24 25](https://user-images.githubusercontent.com/1496761/80336659-34a5c480-8858-11ea-8883-b47e3942d24c.png)

Thanks!

**Comment by swyxio** [comment]
hi! oh dear, i have no idea. this looks like a pa11y time out. if you enable `debugMode` how many `htmlFilePaths` do you have? i bet its a lot.

in https://github.com/sw-yx/netlify-plugin-a11y/blob/master/plugin/pluginCore.js#L9 i tried to parallel run all of them at once. this was a naive impl, we probably want to process them in a queue limited by number of available cores. i was kinda dreading this, i dont really know how to do this but ive seen it done, e.g. https://github.com/mrkishi/sapper/blob/9dd63ab760cf225dee7b999e454b2786fef0eeb5/src/api/export.ts#L92

**Comment by matuzo** [comment]
Thanks for the quick reply! 
Oh, I assumed that if I define `checkPaths = ['/']`, only the home page will be checked but it checks the whole folder and all subfolders. My bad, sorry.

I've changed my settings and now it works like a charm. Thanks :)
```
 checkPaths = [
    '/index.html',
    '/html/index.html',
    '/css/properties/index.html',
    '/html/elements/a/index.html'
  ]
```
