### ISSUE TITLE
Broken link to Axe documentation for audio captions

### ISSUE THREAD

**Issue by dippedrusk** [netlify-labs/netlify-plugin-a11y#66]
**Describe the bug**
The "<audio> elements must have a captions track" error links to https://dequeuniversity.com/rules/axe/4.3/audio-caption?application=axeAPI which says "No matching rule for "audio-caption" in axe 4.3."

**To Reproduce**
1. Create a HTML snippet including `<audio><source src="/some/file.wav"></audio>`
2. Run the a11y plugin

**Expected behavior**
It should point to a link that explains how to add captions to your audio.

**Screenshots**
![Screen Shot 2021-11-24 at 2 26 23 AM](https://user-images.githubusercontent.com/15020857/143155127-96a06bff-2e13-4f83-ae5e-683eb0d71da2.png)

**Desktop (please complete the following information):**
Not applicable

**Smartphone (please complete the following information):**
Not applicable

**Additional context**
I couldn't find this in any of the axe 4.3 rules. I did find https://dequeuniversity.com/rules/axe/4.3/video-caption which is not the same thing. Also I thought there wasn't native support for captions with audio tags in HTML which is why I describe the audio in the text leading up to it. Yes, I'm using version 1.0.0-alpha.4 of the plugin.

**Comment by mxmason** [comment]
Thanks for flagging this, @vgautam! Because these links are generated by `pa11y` (and perhaps from within `pa11y`, by `axe-core`) this is not something we can fix. 😞 

I will make a note of this issue in future documentation, should anyone else encounter it!
